version: '3.9'

services:
  backend:
    build: "backend"
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: orders
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
